"""Coverage by layer and by song. Writes reports/coverage.md and the status column of songs.csv.
Deterministic: same data, same output."""
import csv, os
from common import *

EXPERT = ["mcgill_billboard", "harmonix", "rolling_stone_dt", "rolling_stone_tdc", "isophonics"]


def layers(sid):
    d = os.path.join(SONGS, sid)
    has = lambda p: os.path.exists(os.path.join(d, p))
    facts = read_json(os.path.join(d, "facts.json")) or {}
    cover = (read_json(os.path.join(d, "cover", "cover.json")) or {}).get("images", {})
    st = read_json(os.path.join(d, "structure.json")) or {}
    ch = read_json(os.path.join(d, "chords.json")) or {}
    st_src = [s["key"] for s in st.get("sources", [])]
    ch_src = [s["key"] for s in ch.get("sources", [])]
    return {
        "wikidata": "wikidata" in facts, "musicbrainz": "musicbrainz" in facts,
        "wikipedia": has("wikipedia.json"), "charts": has("charts.json"),
        "lyrics": has("lyrics/timed.lrc") or has("lyrics/plain.txt"), "audio": has("audio.json"),
        "cover_single": bool(cover.get("single", {}).get("file")),
        "cover_album": bool(cover.get("album", {}).get("file")),
        "cover_itunes": bool(cover.get("itunes", {}).get("file")),
        "lineage": has("lineage.json"),
        "structure_expert": any(k in EXPERT for k in st_src),
        "structure_crowd": "chordonomicon" in st_src,
        "chords_expert": any(k in EXPERT for k in ch_src),
        "chords_crowd": "chordonomicon" in ch_src,
        "_struct_sources": st_src, "_chord_sources": ch_src,
    }


LABEL = {"wikidata": "Wikidata", "musicbrainz": "MusicBrainz", "wikipedia": "Wikipedia article",
         "charts": "Billboard chart run", "lyrics": "Timed lyrics (LRCLIB)", "audio": "Preview audio measures",
         "cover_single": "Single sleeve (Cover Art Archive)", "cover_album": "Album cover (Cover Art Archive)",
         "cover_itunes": "Digital artwork (iTunes)", "lineage": "Lineage (SecondHandSongs)",
         "structure_expert": "Structure, expert", "structure_crowd": "Structure, crowd (Chordonomicon)",
         "chords_expert": "Chords, expert", "chords_crowd": "Chords, crowd (Chordonomicon)"}
STATUS = [("facts", ["wikidata", "musicbrainz"]), ("wikipedia", ["wikipedia"]), ("charts", ["charts"]),
          ("lyrics", ["lyrics"]), ("audio", ["audio"]), ("cover", ["cover_single", "cover_album", "cover_itunes"]),
          ("lineage", ["lineage"]), ("structure", ["structure_expert", "structure_crowd"]),
          ("chords", ["chords_expert", "chords_crowd"])]


def main():
    songs = load_songs()
    rows = {s["id"]: layers(s["id"]) for s in songs}
    n = len(songs)
    out = ["# Coverage", "", "Generated by `tools/coverage.py`. %d songs." % n, "", "## By layer", "",
           "| Layer | Songs | Share |", "|---|---|---|"]
    for k, lab in LABEL.items():
        c = sum(r[k] for r in rows.values())
        out.append("| %s | %d | %d%% |" % (lab, c, round(100 * c / n)))
    src = {}
    for r in rows.values():
        for k in set(r["_struct_sources"] + r["_chord_sources"]):
            src[k] = src.get(k, 0) + 1
    out += ["", "## Structure and chord sources", "", "| Source | Songs |", "|---|---|"]
    out += ["| %s | %d |" % (k, v) for k, v in sorted(src.items(), key=lambda x: (-x[1], x[0]))]
    out += ["", "## By song", "", "| Song | " + " | ".join(l for l, _ in STATUS) + " | Structure / chord sources |",
            "|---|" + "---|" * (len(STATUS) + 1)]
    for s in songs:
        r = rows[s["id"]]
        cells = []
        for name, keys in STATUS:
            got = sum(r[k] for k in keys)
            cells.append("yes" if got == len(keys) else ("part" if got else "-"))
        srcs = ", ".join(sorted(set(r["_struct_sources"] + r["_chord_sources"]))) or "-"
        out.append("| %s %s | %s | %s |" % (s["chart_year"], s["title"], " | ".join(cells), srcs))
        s["status"] = "; ".join(["listed"] + [name for name, keys in STATUS if any(r[k] for k in keys)])
    os.makedirs(os.path.join(ROOT, "reports"), exist_ok=True)
    with open(os.path.join(ROOT, "reports", "coverage.md"), "w") as f:
        f.write("\n".join(out) + "\n")
    with open(os.path.join(ROOT, "songs.csv"), "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=list(songs[0]))
        w.writeheader(); w.writerows(songs)


if __name__ == "__main__":
    main()
